apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: broadcaster
          env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: broadcaster
                key: token
          - name: DISCORD_CHANNEL_ID
            valueFrom:
              secretKeyRef:
                name: broadcaster
                key: channel
