apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- ./backup
patches:
- path: broadcaster/deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: fallmx/broadcaster
  newTag: fc4293abece5d86bb69d64eff2dcedcb861d1528
- name: PROJECT/TODO_APP
  newName: fallmx/todo-app
  newTag: fc4293abece5d86bb69d64eff2dcedcb861d1528
- name: PROJECT/TODO_BACKEND
  newName: fallmx/todo-backend
  newTag: fc4293abece5d86bb69d64eff2dcedcb861d1528
