apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- ./backup
patches:
- path: broadcaster/deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: fallmx/broadcaster
  newTag: 97d7713426282f76c15c180c5cfd08154770cc24
- name: PROJECT/TODO_APP
  newName: fallmx/todo-app
  newTag: 97d7713426282f76c15c180c5cfd08154770cc24
- name: PROJECT/TODO_BACKEND
  newName: fallmx/todo-backend
  newTag: 97d7713426282f76c15c180c5cfd08154770cc24
