apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8084
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 8084
          env:
          - name: PORT
            value: "8084"
          - name: GIN_MODE
            value: release
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: todo-backend-postgres
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-backend-postgres
                key: password
          - name: DB_HOST
            value: todo-backend-postgres
          - name: DB_PORT
            value: "5432"
          - name: NATS_URL
            value: nats://nats:4222
