apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- deployment.yaml
- service.yaml
- cronjob-random-wikipedia.yaml
secretGenerator:
  - name: todo-backend-postgres
    literals:
      - username=postgres
      - password=postgres
generatorOptions:
  disableNameSuffixHash: true
