apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: todo-backup
          containers:
          - name: todo-backup
            image: postgres:18
            volumeMounts:
              - name: backups
                mountPath: /mnt/backups
            env:
            - name: PGHOST
              value: todo-backend-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: todo-backend-postgres
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-backend-postgres
                  key: password
            command:
            - /bin/sh
            - -c
            - |
              set -e

              DATE=$(date +%F)
              FILE=/mnt/backups/backup-${DATE}.sql.gz

              pg_dump | gzip > "$FILE"
              echo "backup written to $FILE"
